#9 appbar
RadioAktywne/ra-app pull request #17
Opened 2023-05-23 21:12 UTC by tymwitko

2023-05-30 15:47 UTC, Kszesiek requested changes

2023-05-30 20:17 UTC, tymwitko commented on mobile/assets/temp.png
Right, deleted

2023-05-30 20:17 UTC, tymwitko commented on mobile/lib/components/ra_appbar.dart
> +      toolbarHeight: height.toDouble(),
Done

2023-05-30 20:17 UTC, tymwitko commented on mobile/lib/components/ra_appbar.dart
> +        iconButton!
Done

2023-05-30 20:18 UTC, tymwitko commented on mobile/lib/components/ra_appbar.dart
> +              iconPath!,
Done with null safety

2023-06-01 10:41 UTC, Kszesiek approved these changes
Looks right

2023-06-01 16:22 UTC, merged