Teraz gramy button
RadioAktywne/ra-app pull request #74
Opened 2024-07-19 19:16 UTC by tymwitko

Added functionality to the "Teraz gramy" button. The main icon acts the same way as the main page player button, thus toggling the current radio stream. Below the icon there's a "Teraz gramy" widget title with the stream's description (RDS) below
![Screenshot_20240719_211427](https://github.com/user-attachments/assets/ba5fd089-81af-4c0a-9ef6-fcd84b7840a2)
![Screenshot_20240719_211433](https://github.com/user-attachments/assets/fb463231-c0a8-4e64-b82a-9fd8a0f0bd7c)

2024-07-20 11:06 UTC, julianuziemblo requested changes
Works okay, there is an issue with the button being centered. Also, there is a lot of unnecessary code, which makes this much less readable, should be refactored.

2024-07-20 11:06 UTC, julianuziemblo commented on mobile/lib/components/teraz_gramy/teraz_gramy_widget.dart
> +          },
Also here - after the aforementioned correction, both versions have the same text above - "Teraz gramy", so this should really only be a switch between the Text('No stream title') and the StreamTitle widgets, kinda like so:

```dart
    children: [
        Text(
            'Teraz gramy',
             style: context.textStyles.textPlayer.copyWith(
               color: context.colors.highlightGreen,
             ),
           ),
           switch (audioHandler) {
             null => Text(
                 'No stream title',
                 style: context.textStyles.textMedium.copyWith(
                   height: 1.5,
                 ),
               ),
             _ => StreamTitle(
                 audioHandler: audioHandler,
                 width: MediaQuery.of(context).size.width,
                 style: context.textStyles.textMedium.copyWith(
                   height: 1.5,
                 ),
               ),
           },
         ],
```

2024-07-28 10:46 UTC, Tombiczek commented
It seems like it doesn't work on iOS. I get:
```
flutter: stream name:
flutter: stream title:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (-11850) Operation Stopped
#0      AudioPlayer._load (package:just_audio/just_audio.dart:870:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1494:28)
<asynchronous suspension>
flutter: stream name:
flutter: stream title:
[ERROR:flutter/impeller/base/validation.cc(59)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested mip_count 4 exceeds maximum supported for size (4, 5)
flutter: stream name:
flutter: stream title:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (-11850) Operation Stopped
#0      AudioPlayer._load (package:just_audio/just_audio.dart:870:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1494:28)
<asynchronous suspension>
```

Either playing the radio from the `Teraz gramy` button as well as the bottom bar does not work.

2024-08-01 13:29 UTC, Kszesiek requested changes
Minor nitpicks, good job overall

2024-08-01 21:05 UTC, Kszesiek approved these changes
Approve

2024-08-01 21:07 UTC, julianuziemblo approved these changes
LGTM! (_of course..._)

2024-08-01 21:07 UTC, merged